// threads.js — Musubi: threads are MEANDERING PATHS across the canvas.
//
// A Thread carries a pre-computed polyline (pathPoints) in WORLD-space pixels
// (absolute: {x, y}, where y is document-space and x is screen-space center
// offset is handled by absolute x). It's sampled to draw, to fade, and to
// place beads (images) somewhere along its arclength.
//
// Paths are GENERATED by the `generateMeander` helper: a random walk with
// angular inertia + sinusoidal bias, which produces loops, hairpins and
// soft curves like an aerial river map. Threads can start and end anywhere
// on the page — not just the central axis.

(function (global) {
  // ---- Mobile detection (cached, refreshed on resize) -----------------
  // Used by the breathing/wind code to drop a second sine harmonic on phones,
  // halving the per-sample sin() count. Cached to avoid repeated DOM reads.
  let _isMobileCached = null;
  function isMobile() {
    if (_isMobileCached === null) _isMobileCached = window.innerWidth < 820;
    return _isMobileCached;
  }
  if (typeof window !== 'undefined') {
    window.addEventListener('resize', () => { _isMobileCached = window.innerWidth < 820; });
  }

  // ---- Meander generator ----------------------------------------------
  // Strategy: a real river meander serpentines AROUND a main axis — it never
  // crosses itself. So the path is ALWAYS a pure perpendicular offset from
  // a straight spine; no longitudinal wobble (which causes loops), no
  // harmonics large enough to make the curve fold over.
  //
  //   spine(t) = lerp(start, end, t)
  //   perpOffset(t) = A(t) * [ sin(2π t·L / λ + φ) + 0.3·sin(2π t·L / λ·2.3 + φ2) ]
  //   point(t) = spine(t) + perpOffset(t) · perpendicular
  //
  // The KEY to looking river-like:
  //   - amplitude is significant (much wider than the line itself)
  //   - wavelength is generous (slow, not nervous)
  //   - NO longitudinal offset — the curve never backs up
  //   - light secondary harmonic for natural asymmetry
  //
  // opts:
  //   startX, startY, endX, endY
  //   amplitude    — base perpendicular amplitude (px). default 260
  //   wavelength   — px along spine per full oscillation. default 700
  //   secondary    — magnitude of the 2.3× harmonic. default 0.28 (keep < 0.45)
  //   resolution   — samples per unit spine length. default 0.4
  //   seed
  function makeRng(seed) {
    let s = (seed | 0) || Math.floor(Math.random() * 1e9);
    return function () {
      s = (s * 9301 + 49297) | 0;
      s = s >>> 0;
      return (s % 233280) / 233280;
    };
  }

  function generateMeander(opts) {
    const startX = opts.startX, startY = opts.startY;
    const endX = opts.endX, endY = opts.endY;
    const amplitude = opts.amplitude != null ? opts.amplitude : 260;
    const wavelength = opts.wavelength || 700;
    const secondary = opts.secondary != null ? opts.secondary : 0.28;
    const resolution = opts.resolution || 0.4;
    const rng = makeRng(opts.seed);

    const dx = endX - startX, dy = endY - startY;
    const spineLen = Math.hypot(dx, dy);
    if (spineLen < 1) {
      return { points: [{ x: startX, y: startY }, { x: endX, y: endY }], cum: new Float32Array([0, 0]), length: 0 };
    }
    const sx = dx / spineLen, sy = dy / spineLen;    // spine tangent (unit)
    const nx = -sy, ny = sx;                           // spine normal

    // Random phase per thread so they look different even with same params
    const phi1 = rng() * Math.PI * 2;
    const phi2 = rng() * Math.PI * 2;

    // Sample along spine
    const samples = Math.max(80, Math.ceil(spineLen * resolution));
    const points = new Array(samples + 1);

    for (let i = 0; i <= samples; i++) {
      const t = i / samples;
      const spX = startX + dx * t;
      const spY = startY + dy * t;

      // Amplitude envelope — fades smoothly at both ends so the curve
      // eases into and out of the spine endpoints
      const envShape = Math.sin(t * Math.PI);
      const env = Math.pow(envShape, 0.55);

      const k1 = (2 * Math.PI) / wavelength;
      const k2 = (2 * Math.PI) / (wavelength / 2.3);

      // PURE perpendicular offset — no longitudinal component, no crossing
      const perp = amplitude * env * (
        Math.sin(k1 * (t * spineLen) + phi1) +
        secondary * Math.sin(k2 * (t * spineLen) + phi2)
      );

      points[i] = {
        x: spX + nx * perp,
        y: spY + ny * perp,
      };
    }

    points[0] = { x: startX, y: startY };
    points[samples] = { x: endX, y: endY };

    const cum = new Float32Array(points.length);
    cum[0] = 0;
    for (let i = 1; i < points.length; i++) {
      cum[i] = cum[i - 1] + Math.hypot(points[i].x - points[i - 1].x, points[i].y - points[i - 1].y);
    }
    return { points, cum, length: cum[cum.length - 1] };
  }

  // ---- Scroll-driven wind energy --------------------------------------
  // The page scroll IS the wind: when the user scrolls fast, breath amplitude
  // ramps up; when idle, it relaxes back to a soft floor. State lives at module
  // scope so Thread.sampleArc can read it cheaply (no per-call plumbing through
  // World/Thread). Smoothing is asymmetric: fast attack, slow release, so the
  // threads "settle" instead of cutting off when scroll stops.
  let scrollEnergy = 0;          // 0 = calm, 1 = strong gust
  let _lastCamY = null;
  let _lastTime = 0;
  function _updateScrollEnergy(camY, time) {
    if (_lastCamY !== null && _lastTime > 0) {
      const dt = Math.max(1, time - _lastTime);
      const velocity = Math.abs(camY - _lastCamY) / dt;   // px per ms
      // Map velocity to 0..1. ~2.2 px/ms ≈ briskly scrolling with a wheel.
      const target = Math.min(1, velocity / 2.2);
      // Attack fast (engage), release slow (graceful settle ~0.5–1s)
      const rate = target > scrollEnergy ? 0.22 : 0.035;
      scrollEnergy += (target - scrollEnergy) * rate;
    }
    _lastCamY = camY;
    _lastTime = time;
  }

  // ---- Thread ---------------------------------------------------------
  let THREAD_ID = 0;
  class Thread {
    constructor(opts) {
      this.id = ++THREAD_ID;
      // A pre-generated path: {points: [{x,y}], cum: Float32Array, length: number}
      // x is absolute screen-X in the fixed overlay; y is DOCUMENT-space worldY.
      this.path = opts.path;
      // Birth/death along the path's arclength (or use full)
      this.birthArc = opts.birthArc != null ? opts.birthArc : 0;
      this.deathArc = opts.deathArc != null ? opts.deathArc : this.path.length;

      // Style
      this.hue = opts.hue != null ? opts.hue : 358;
      this.sat = opts.sat != null ? opts.sat : 78;
      this.light = opts.light != null ? opts.light : 34;
      this.thickness = opts.thickness || 1.0;
      this.blurPx = opts.blurPx || 0;
      this.baseAlpha = opts.baseAlpha != null ? opts.baseAlpha : 0.58;
      this.glowAlpha = opts.glowAlpha != null ? opts.glowAlpha : 0.18;

      // Wind morph — perpendicular offset varying along arclength so the
      // meander loops themselves ripple. Spatial wavelengths chosen so 2–3
      // ripples fit inside a typical viewport (you can SEE the thread undulate).
      // Default amp ~18px against meander amplitudes of 160–360px (~5–11%):
      // ripples are clearly visible but never overpower the meander shape.
      this.breatheAmp = opts.breatheAmp != null ? opts.breatheAmp : 18;
      this.breatheFreq = opts.breatheFreq || 0.0008;  // ~8s temporal cycle
      this.breathePhase = Math.random() * 1000;

      // The Y-range the thread occupies (for envelope)
      let minY = Infinity, maxY = -Infinity;
      for (const p of this.path.points) { if (p.y < minY) minY = p.y; if (p.y > maxY) maxY = p.y; }
      this.minY = minY; this.maxY = maxY;

      // For bead placement along the path
      this.pathBeads = [];
    }

    // Interpolated point at arclength s (0..length). Returns {x, y, tx, ty}
    // where (tx, ty) is the unit tangent.
    sampleArc(s, time) {
      const { points, cum, length } = this.path;
      if (s <= 0) {
        const p0 = points[0], p1 = points[1];
        const dx = p1.x - p0.x, dy = p1.y - p0.y;
        const l = Math.hypot(dx, dy) || 1;
        return { x: p0.x, y: p0.y, tx: dx / l, ty: dy / l };
      }
      if (s >= length) {
        const pN = points[points.length - 1], pM = points[points.length - 2];
        const dx = pN.x - pM.x, dy = pN.y - pM.y;
        const l = Math.hypot(dx, dy) || 1;
        return { x: pN.x, y: pN.y, tx: dx / l, ty: dy / l };
      }
      // Binary search in cum
      let lo = 0, hi = cum.length - 1;
      while (lo < hi - 1) {
        const mid = (lo + hi) >> 1;
        if (cum[mid] <= s) lo = mid; else hi = mid;
      }
      const seg = cum[hi] - cum[lo];
      const t = seg > 0 ? (s - cum[lo]) / seg : 0;
      const p0 = points[lo], p1 = points[hi];
      const dx = p1.x - p0.x, dy = p1.y - p0.y;
      const l = Math.hypot(dx, dy) || 1;
      // Subtle morph — displace perpendicular to tangent (cheap: no breath if amp=0).
      // Both sine terms include `s` (arclength), so different parts of the thread
      // get DIFFERENT offsets at the same instant: the curve flexes locally rather
      // than sliding as a rigid body. Spatial wavelengths (~2100px and ~4200px)
      // are tuned so 2–3 ripples fit inside a typical viewport — the user
      // actually perceives undulation traveling along the thread, not just a
      // blanket sway. Temporal cycle ~8s keeps it elegant. Mobile drops the
      // second harmonic: one sin() per sample, same character.
      //
      // Amplitude is modulated by scrollEnergy: 0.85× when idle (clearly alive,
      // close to the base amp) up to ~2.25× when scrolling briskly (energetic
      // gust). Idle floor is intentionally high so the threads keep undulating
      // visibly at rest — scroll just adds a stronger gust on top.
      let px = p0.x + dx * t;
      let py = p0.y + dy * t;
      // Breath sempre ativa — no mobile a página agora roda só com 2 fios,
      // então o custo de manter a respiração viva é insignificante (~400
      // sin() por frame). E sem ela a página perde o "pulso" que é o ponto
      // do conceito musubi.
      if (this.breatheAmp > 0) {
        // Mobile: praticamente sem amplificação por scrollEnergy. O ramp de
        // ~2.25× durante o scroll (perpendicular ao fio) era a causa principal
        // do "samba" lateral percebido em tela estreita. Mantém um floor 0.95
        // pra respiração não morrer e um empurrãozinho de 0.15 quando há
        // gust — character mas não wobble.
        // Desktop continua com o ramp dramático original: ali o efeito fica
        // legal porque os fios têm muito mais espaço lateral pra dançar.
        const ampMul = isMobile()
          ? 0.95 + scrollEnergy * 0.15
          : 0.85 + scrollEnergy * 1.4;
        const w1 = Math.sin(time * this.breatheFreq + this.breathePhase + s * 0.003);
        let breath = w1 * this.breatheAmp;
        if (!isMobile()) {
          // Lower temporal + longer spatial: a slow tide modulating the main ripple.
          const w2 = Math.sin(time * this.breatheFreq * 0.6 + this.breathePhase * 1.7 + s * 0.0015);
          breath += w2 * this.breatheAmp * 0.45;
        }
        breath *= ampMul;
        const nx = -dy / l, ny = dx / l;
        px += nx * breath;
        py += ny * breath;
      }
      return { x: px, y: py, tx: dx / l, ty: dy / l };
    }

    // Envelope: fades based on whether the thread is in view (with margin)
    envelopeAt(camY, viewportH) {
      const top = camY - 200;
      const bottom = camY + viewportH + 200;
      if (this.maxY < top || this.minY > bottom) return 0;
      return 1;
    }
  }

  // ---- World ----------------------------------------------------------
  class World {
    constructor(canvas, opts = {}) {
      this.canvas = canvas;
      this.ctx = canvas.getContext('2d', { alpha: true });
      this.W = 0; this.H = 0; this.dpr = 1;
      this.threads = [];
      this.time = 0;
      this.camY = 0;
      this.worldHeight = opts.worldHeight || 6000;
      this._resize();
      window.addEventListener('resize', () => this._resize());
    }

    _resize() {
      const isMobile = window.innerWidth < 820;
      // Mobile: cap DPR at 1.0 — phones ship 2.5–3× DPR by default; clamping
      // to 1.0 cuts the pixel work the canvas does by ~7–9× vs. native and
      // ~2.25× vs. our previous 1.5 cap. The threads are soft/blurry by design,
      // so the resolution loss is invisible while the perf gain is enormous.
      this.dpr = Math.min(window.devicePixelRatio || 1, isMobile ? 1.0 : 2);
      this.W = window.innerWidth;
      this.H = window.innerHeight;
      this.canvas.style.width = this.W + 'px';
      this.canvas.style.height = this.H + 'px';
      this.canvas.width = this.W * this.dpr;
      this.canvas.height = this.H * this.dpr;
      this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
      this._isMobile = isMobile;
    }

    add(thread) { this.threads.push(thread); return thread; }

    step(camY, time) {
      _updateScrollEnergy(camY, time);
      this.camY = camY;
      this.time = time;
    }

    draw() {
      const ctx = this.ctx;
      ctx.clearRect(0, 0, this.W, this.H);
      for (const th of this.threads) {
        const env = th.envelopeAt(this.camY, this.H);
        if (env < 0.005) continue;
        this._drawThread(th, env);
      }
    }

    _drawThread(th, env) {
      const ctx = this.ctx;
      const viewTop = this.camY;
      const viewBottom = viewTop + this.H;
      // Mobile: even coarser sampling — 30 vs 10 desktop. Threads are smooth
      // sweeping curves, the resulting line still reads as a curve.
      const ARC_STEP = this._isMobile ? 30 : 10;
      const FADE_ARC = 260;
      const { birthArc, deathArc } = th;
      const totalArc = deathArc - birthArc;
      if (totalArc <= 0) return;
      const ss = (t) => t * t * (3 - 2 * t);

      // Pre-sample; skip samples whose y is far off-screen to save draw calls
      const numSteps = Math.ceil(totalArc / ARC_STEP);
      const pts = new Array(numSteps + 1);
      const MARGIN = 80;
      for (let i = 0; i <= numSteps; i++) {
        const sArc = Math.min(birthArc + i * ARC_STEP, deathArc);
        const p = th.sampleArc(sArc, this.time);
        const arcFromStart = sArc - birthArc;
        const arcToEnd = deathArc - sArc;
        const fadeIn = Math.max(0, Math.min(1, arcFromStart / FADE_ARC));
        const fadeOut = Math.max(0, Math.min(1, arcToEnd / FADE_ARC));
        const alphaLocal = ss(Math.min(fadeIn, fadeOut));
        const sy = p.y - viewTop;
        pts[i] = {
          x: p.x,
          y: sy,
          a: alphaLocal,
          onScreen: sy > -MARGIN && sy < this.H + MARGIN,
        };
      }

      ctx.lineCap = 'round';
      ctx.lineJoin = 'round';
      // Blur filter is a major perf cost on mobile GPUs (forces an offscreen
      // texture per stroke). Skip it on phones — visually nearly identical
      // because thread.blurPx is at most 1.8 and lines are already soft.
      ctx.filter = (!this._isMobile && th.blurPx) ? `blur(${th.blurPx}px)` : 'none';
      const hue = th.hue;  // no time-based hue shift (cheaper, visually identical)

      // Glow pass — skipped entirely on mobile. We compensate with a slightly
      // thicker core stroke and a hue/light tweak so the thread still reads
      // soft instead of stark. This single change roughly halves the stroke
      // work per thread per frame.
      if (!this._isMobile) {
        const thickGlow = 2.8 * th.thickness;
        ctx.lineWidth = thickGlow;
        const lGlow = Math.min(62, th.light + 16);
        let curAlpha = -1;
        ctx.beginPath();
        for (let i = 0; i < numSteps; i++) {
          const p0 = pts[i], p1 = pts[i + 1];
          if (!p0.onScreen && !p1.onScreen) continue;
          const segA = Math.min(p0.a, p1.a) * env * th.glowAlpha;
          if (segA < 0.004) continue;
          const qa = Math.round(segA * 200) / 200; // quantize alpha into buckets
          if (qa !== curAlpha) {
            if (curAlpha >= 0) ctx.stroke();
            ctx.strokeStyle = `hsla(${hue}, ${th.sat}%, ${lGlow}%, ${qa.toFixed(3)})`;
            ctx.beginPath();
            curAlpha = qa;
          }
          ctx.moveTo(p0.x, p0.y);
          ctx.lineTo(p1.x, p1.y);
        }
        if (curAlpha >= 0) ctx.stroke();
      }

      // Core pass. Mobile uses a slightly thicker stroke + brighter base to
      // make up for the missing glow halo.
      const thickCore = (this._isMobile ? 1.45 : 1.15) * th.thickness;
      ctx.lineWidth = thickCore;
      const baseLight = this._isMobile ? Math.min(58, th.light + 6) : th.light;
      const baseAlphaMul = this._isMobile ? 1.08 : 1;
      let curAlpha = -1;
      ctx.beginPath();
      for (let i = 0; i < numSteps; i++) {
        const p0 = pts[i], p1 = pts[i + 1];
        if (!p0.onScreen && !p1.onScreen) continue;
        const segA = Math.min(p0.a, p1.a) * env * th.baseAlpha * baseAlphaMul;
        if (segA < 0.004) continue;
        const qa = Math.round(segA * 200) / 200;
        if (qa !== curAlpha) {
          if (curAlpha >= 0) ctx.stroke();
          ctx.strokeStyle = `hsla(${hue}, ${th.sat}%, ${baseLight}%, ${qa.toFixed(3)})`;
          ctx.beginPath();
          curAlpha = qa;
        }
        ctx.moveTo(p0.x, p0.y);
        ctx.lineTo(p1.x, p1.y);
      }
      if (curAlpha >= 0) ctx.stroke();

      ctx.filter = 'none';
    }

    // Position a bead: given a thread and an arclength s, return its screen pos.
    beadPositionAtArc(thread, s) {
      const p = thread.sampleArc(s, this.time);
      const sy = p.y - this.camY;
      if (sy < -300 || sy > this.H + 300) return null;
      // Fade based on position within [birthArc..deathArc]
      const FADE = 260;
      const ss = (t) => t * t * (3 - 2 * t);
      const fadeIn = Math.max(0, Math.min(1, (s - thread.birthArc) / FADE));
      const fadeOut = Math.max(0, Math.min(1, (thread.deathArc - s) / FADE));
      const alpha = ss(Math.min(fadeIn, fadeOut));
      if (alpha < 0.02) return null;
      // Image rotates to align with the tangent direction (perpendicular offset is natural)
      const angle = Math.atan2(p.ty, p.tx);
      return { x: p.x, y: sy, angle, alpha };
    }
  }

  // ---- Geometria: interseção segmento × segmento -----------------------
  // Algoritmo padrão (cross-product based). Devolve {x, y, t, u} se os
  // segmentos se cruzam — t e u são as posições paramétricas (0..1) ao
  // longo de seg1 e seg2. null se forem paralelos ou se a interseção
  // cair fora dos segmentos.
  function segIntersect(p1, p2, p3, p4) {
    const x1 = p1.x, y1 = p1.y, x2 = p2.x, y2 = p2.y;
    const x3 = p3.x, y3 = p3.y, x4 = p4.x, y4 = p4.y;
    const denom = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4);
    if (Math.abs(denom) < 1e-9) return null;
    const t = ((x1 - x3) * (y3 - y4) - (y1 - y3) * (x3 - x4)) / denom;
    const u = -((x1 - x2) * (y1 - y3) - (y1 - y2) * (x1 - x3)) / denom;
    if (t < 0 || t > 1 || u < 0 || u > 1) return null;
    return { x: x1 + t * (x2 - x1), y: y1 + t * (y2 - y1), t, u };
  }

  // ---- Cruzamentos entre dois fios -------------------------------------
  // Itera os segmentos de cada path com stride (paths têm 200–2000 pontos)
  // e devolve os pontos onde se cruzam, junto com o arc-length em cada
  // fio (sA, sB) — usado pra ancorar fotos nessa posição enquanto os
  // fios respiram. Bbox quick-reject mantém o custo plano.
  function findThreadIntersections(threadA, threadB) {
    const out = [];
    const pa = threadA.path.points, ca = threadA.path.cum;
    const pb = threadB.path.points, cb = threadB.path.cum;
    const SA = Math.max(2, Math.floor(pa.length / 220));
    const SB = Math.max(2, Math.floor(pb.length / 220));
    for (let i = 0; i + SA < pa.length; i += SA) {
      const a1 = pa[i], a2 = pa[i + SA];
      const aMinY = Math.min(a1.y, a2.y), aMaxY = Math.max(a1.y, a2.y);
      const aMinX = Math.min(a1.x, a2.x), aMaxX = Math.max(a1.x, a2.x);
      for (let j = 0; j + SB < pb.length; j += SB) {
        const b1 = pb[j], b2 = pb[j + SB];
        const bMinY = Math.min(b1.y, b2.y), bMaxY = Math.max(b1.y, b2.y);
        if (bMaxY < aMinY || bMinY > aMaxY) continue;
        const bMinX = Math.min(b1.x, b2.x), bMaxX = Math.max(b1.x, b2.x);
        if (bMaxX < aMinX || bMinX > aMaxX) continue;
        const ix = segIntersect(a1, a2, b1, b2);
        if (ix) {
          const sA = ca[i] + ix.t * (ca[i + SA] - ca[i]);
          const sB = cb[j] + ix.u * (cb[j + SB] - cb[j]);
          out.push({ x: ix.x, y: ix.y, sA, sB });
        }
      }
    }
    return out;
  }

  global.Musubi = { Thread, World, generateMeander, segIntersect, findThreadIntersections };
})(window);
